baseURL = 'https://prayag2.github.io/'
languageCode = 'en-us'
title = 'Prayag Jain'
theme = 'shibui'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  email = "prayagjain2@gmail.com"
  comments = true
  math = true

[services]
  [services.disqus]
    shortname = 'prayag-jain'
