baseURL = 'https://prayag2.github.io/'
languageCode = 'en-US'
title = 'Prayag Jain'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = 'GitHub'
    url = 'https://github.com/prayag2'
    weight = 40
    [menus.main.params]
      target = '_blank'

  [[menus.main]]
    name = 'KDE'
    url = 'https://invent.kde.org/prayag'
    weight = 50
    [menus.main.params]
      target = '_blank'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.93.0'

